export enum EntityNames {
  User = "user",
  Profile = "profile",
  Category = "category",
  Blog = "blog",
  BlogCategory = "blog_category",
  FoodCategory = "food_category",
  Food = "food",
  BlogLikes = "blog_like",
  BlogComments = "blog_comments",
  Membership = "membership",
  MembershipPlan = "membership_plan",
  Basket = "basket",
  Payment = "payment",
  Order = "order",
  OrderItems = "order-item",
  UserWeight = "user_wight",
  FoodPlan = "food_plan",
  SubPlan = "sub_plan",
  Meal = "meal",
  MealItem = "meal_item",
}
